# Generated by Django 4.0 on 2022-01-07 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRoomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField(choices=[('commented', 'commented'), ('upvoted', 'upvoted'), ('downvoted', 'downvoted'), ('answered', 'answered')], default='answered', max_length=15)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('post', models.TextField(choices=[('answer', 'answer'), ('question', 'question')], default='question', max_length=9)),
                ('post_id', models.UUIDField(default=uuid.uuid4)),
                ('description', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='users.users')),
            ],
        ),
    ]
