# Generated by Django 3.2.5 on 2021-12-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
